function dthelp() {
    echo "--------------"
    echo ""
    echo "DOTFILES HELP:"
    echo ""
    echo "--------------"
    echo ""
    echo "FUNCTIONS:"
    echo "aa_256 — Print all 256 colors"
    echo ""
    echo "bootstrap-eslint — Copy default .eslintrc to current folder"
    echo ""
    echo "cdf — cd into whatever is the forefront Finder window"
    echo "cdgr — cd into git repo root"
    echo "cf [<dir:pwd>] — Count files"
    echo "codepoint <char> — Get a character’s Unicode code point: £ → \x00A3"
    echo "ctxt [<from:WINDOWS-1251>] [<to:UTF-8>] [<result folder:converted>] — # Convert text. Result folder will be removed and recreated"
    echo ""
    echo "dataurl <file> — Create a data URL from a file"
    echo ""
    echo "exectime <command> — Mesure execution time"
    echo "extract <file> — Extract archives of various types"
    echo ""
    echo "ff — Better find(1)"
    echo "find-exec <pattern> <command> — Find files and exec commands at them. $ find-exec .coffee cat | wc -l"
    echo "fr <where> <from> <to> — Find and replace"
    echo ""
    echo "ghurl — GitHub URL for current repo"
    echo "gitor <new origin url> — Change git origin to given url and make old origin as upstream"
    echo "gitores — Restore remote origin url from upstream url"
    echo "gz <file> — Compare original and gzipped file size"
    echo ""
    echo "imgsize <file> — Quickly get image dimensions from the command line"
    echo ""
    echo "jsonval <file> <key> <count of results> — Get value of property from json file"
    echo ""
    echo "manp <command> — Show man page in Preview.app. $ manp cd"
    echo "mkd <name> — Create a new directory"
    echo "mkdc <name> — Create a new directory and enter it"
    echo "movtogif <file> [<output:out.gif>] [<size:1024>] [<rate:10>] [<colors:128>] — Converts mov to gif"
    echo ""
    echo "npmurl — NPM URL for current package"
    echo "nyan — Print nyan cat"
    echo ""
    echo "ram <app> — Show how much RAM application uses. $ ram safari"
    echo "rndstr <file> — Get random string from file"
    echo ""
    echo "sanitize — Sanitize all filenames in current dir: lowercase, no other characters than letters, digits, dash, underscore and dot"
    echo "server [<port:8000>] — Start an HTTP server from a directory, optionally specifying the port"
    echo "sshfsmount <host> <mount_path> — SSHFS mount"
    echo ""
    echo "up <times> — Cd up number of times"
    echo "upsearch <what> — Search upwards till found. $ upsearch node_modules/.bin/babel-node"
}
