#!/bin/sh

# Print all 256 colors

aa_256() {
  about 'Print all 256 colors'
  example '$ aa_256'
  group 'other'

  ( x=`tput op` y=`printf %$((${COLUMNS}-6))s`;
  for i in {0..256}; do
    o=00$i;
    echo -e ${o:${#o}-3:3} `tput setaf $i;tput setab $i`${y// /=}$x;
  done )
}
