#!/bin/sh

# Converts text

ctxt() {
  about 'Converts text in given files'
  param '1: optional, from (default: WINDOWS-1251)'
  param '2: optional, to (default: UTF-8)'
  param '3: optional, result folder (default: converted)'
  example '$ ctxt'
  example '$ ctxt CP-1250 UTF-8 results'
  group 'convert'

  local from="${1:-WINDOWS-1251}"
  local to="${2:-UTF-8}"
  local res="${3:-converted}"

  rm -rf $res;
  mkdir -p $res;
  find . -type f -exec bash -c 'iconv -f '$from' -t '$to' "{}" > "'$res'/{}"' \;
}
