#!/bin/sh

dmc() {
  about 'Connects to docker-machine'
  param '1: optional, docker-machine name otherwise "default""'
  example '$ dmc'
  example '$ dmc machine-name'
  group 'docker'

  local name=${1:-default}

  eval "$(docker-machine env $name)"
}
