#!/bin/sh

exectime() {
  about 'Measures execution time'
  param '1: command to measure'
  example '$ exectime extract some.zip'
  group 'info'

  local start_time=`date +%s`

  eval '$@'
  hr
  echo ${yellow}run time is $(expr `date +%s` - $start_time)s${reset}
  hr
}
