#!/bin/sh

exectime() {
  about 'Measures execution time'
  param '1: command to measure'
  example '$ exectime extract some.zip'
  group 'info'

  local start_time=`date +%s`

  eval "$@"
  hr
  echo "run time is $(($(date +%s) - start_time))s"
  hr
}
