#!/bin/sh

# Find files and exec commands at them.
# $ fe .coffee cat | wc -l

fe() {
  about 'Find files and exec commands at them'
  param '1: filename to search'
  param '2: command to execute on files'
  example '$ fe .coffee cat | wc -l'
  group 'search'

  find . -type f -iname "*${1:-}*" -exec "${2:-file}" '{}' \;
}
