#!/bin/sh

ghurl() {
  about 'GitHub URL for current repo'
  example '$ ghurl'
  group 'git'

  local remotename="${@:-origin}"
  local remote="$(git remote -v | awk '/^'"$remotename"'.*\(push\)$/ {print $2}')"

  [[ "$remote" ]] || return

  local user_repo="$(echo "$remote" | perl -pe 's/.*:\/\///;s/\.git$//;s/git@//;s/\:/\//')"

  echo "https://$user_repo"
}
