#!/bin/sh

gitores() {
  about 'Restore remote origin url from upstream url'
  example '$ gitores'
  group 'git'

  if [ -d .git ]; then
    if git remote | grep upstream > /dev/null; then
      git remote rm origin
      git remote rename upstream origin
    fi

    git remote -v
  else
    echo "-=-=-=->> There isn't a git repo! <<-=-=-=-"
  fi;
}
