#!/bin/sh

# Quickly get image dimensions from the command line

imgsize() {
  if [[ -f $1 ]]; then
    local height=$(sips -g pixelHeight "$1"|tail -n 1|awk '{print $2}')
    local width=$(sips -g pixelWidth "$1"|tail -n 1|awk '{print $2}')

    echo "${width} x ${height}"
  else
    echo "File not found"
  fi
}
