#!/bin/sh

# Get value of property from json file

jsonval() {
  about 'Get value of property from json file'
  param '1: path to .json file'
  param '2: property to search'
  param '3: optional, number of results (default: all)'
  example '$ jsonval package.json name'
  example '$ jsonval package.json name 1'
  group 'utils'

  local key=$2
  local num=$3

  cat $1 | awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/\042'$key'\042/){print $(i+1)}}}' | tr -d '"' | sed -n ${num}p
}
