#!/bin/sh

# Get value of property from json file

jsonval() {
  local key=$2
  local num=$3

  cat $1 | awk -F"[,:}]" '{for(i=1;i<=NF;i++){if($i~/\042'$key'\042/){print $(i+1)}}}' | tr -d '"' | sed -n ${num}p
}
