#!/usr/bin/env bash

n() {
  about 'Runs given command using binary in node_modules/.bin of the current project (https://github.com/ai/environment)'
  param '1: binary name'
  example '$ n eslint .'
  group 'npm'

  if [ -d $(npm bin) ]; then
    local prog="$1"
    shift
    $(npm bin)/$prog "$@"
  else
    echo 'No node_modules in any dir of current path' 1>&2
    return 1
  fi
}
