#!/usr/bin/env bash

# Runs given command using binary in node_modules/.bin of the current project
# https://github.com/ai/environment

n() {
  if [ -d $(npm bin) ]; then
    local prog="$1"
    shift
    $(npm bin)/$prog "$@"
  else
    echo 'No node_modules in any dir of current path' 1>&2
    return 1
  fi
}
