#!/usr/bin/env bash

n() {
  about 'Runs given command using binary in node_modules/.bin of the current project (https://github.com/ai/environment)'
  param '1: binary name'
  example '$ n eslint .'
  group 'npm'

  if [[ -f bun.lockb ]] then
    command bun "$@"
  elif [[ -f pnpm-lock.yaml ]] then
    command pnpm "$@"
  elif [[ -f yarn.lock ]] then
    command yarn "$@"
  elif [[ -f package-lock.json ]] then
    command npm "$@"
  else
    command pnpm "$@"
  fi
}
