#!/bin/sh

# NPM URL for current package.

npmurl() {
  about 'NPM URL for current package'
  example '$ npmurl'
  group 'npm'

  local package=$(jq -r '.name // empty' package.json 2>/dev/null)

  [[ "$package" ]] || return

  echo "https://npmjs.com/package/$package"
}
