#!/bin/sh

nvm-default() {
  about 'Sets default node version for nvm from current selected version'
  example '$ nvm-default'
  group 'nvm'

  local current=$(nvm_ls_current)

  nvm alias default $current
}
