#!/bin/sh

# Get random string from file

rndstr() {
  about 'Get random string from file'
  param '1: filepath'
  param '2: optional, lines count (default: 1)'
  example '$ rndstr list.txt'
  example '$ rndstr list.txt 10'
  group 'other'

  local count=$2

  : ${count:=-1}
  f=$1; n=$(expr $RANDOM \* `cat $f | wc -l` \/ 32768 + 1); head -n $n $f | tail $count
}
