#!/bin/sh

# Sanitize all filenames in current dir: lowercase, no other characters than letters, digits, dash, underscore and dot

sanitize() {
  about 'Sanitize all filenames in current dir: lowercase, no other characters than letters, digits, dash, underscore and dot'
  example '$ sanitize'
  group 'utils'

  for file in *; do
    local file_clean=`echo $file | tr '[:upper:]' '[:lower:]' | tr -cd "[:alnum:]-_."`

    if [ "${file}" != "${file_clean}" ]; then
      echo "$file > $file_clean"
      mv "$file" "$file_clean"
    fi
  done
}
