#!/bin/sh

# SSHFS mount

sshfsmount() {
  about 'SSHFS mount'
  param '1: ssh server to mount'
  example '$ sshfs root@login.server.com'
  group 'utils'

  local mount_path="/Volumes/sshfs"

  mkdir -p $mount_path

  sshfs -o Ciphers=arcfour -o Compression=yes -o auto_cache,reconnect,defer_permissions,noappledouble -o workaround=nodelaysrv -o cache_stat_timeout=600 -o IdentityFile=~/.ssh/id_rsa $1 $mount_path
}
