#!/bin/sh

# Search upwards till have found

upsearch() {
  local slashes=${PWD//[^\/]/}
  local directory="$PWD"

  for (( n=${#slashes}; n>0; --n )) do
    test -e "$directory/$1" && echo "$directory/$1" && return
    directory="$directory/.."
  done
}
