#!/bin/sh

upsearch() {
  about 'Search upwards till have found'
  param '1: path to search'
  example '$ upsearch node_modules'
  group 'search'

  local slashes=${PWD//[^\/]/}
  local directory="$PWD"

  for (( n=${#slashes}; n>0; --n )) do
    test -e "$directory/$1" && echo "$directory/$1" && return
    directory="$directory/.."
  done
}
