"$schema" = 'https://starship.rs/config-schema.json'

command_timeout = 1000

format = """
$username\
$hostname\
$directory\
$git_branch\
$git_state\
$git_status\
$git_metrics\
$fill\
$bun\
$deno\
$golang\
$nodejs\
$python\
$rust\
$swift\
$cmd_duration\
$line_break\
$character"""

[fill]
symbol = " "

[directory]
style = "blue"
read_only = " "
truncation_length = 4

[character]
success_symbol = '[➜](bold green)'

[git_branch]
symbol = " "
format = "[$symbol$branch]($style) "

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'
style = "cyan"

[git_state]
format = '\([$state( $progress_current/$progress_total)]($style)\) '
style = "bright-black"

[git_metrics]
disabled = false

[cmd_duration]
format = "[$duration]($style)"
style = "yellow"

[bun]
format = "via [$symbol]($style)"

[deno]
format = "via [$symbol]($style)"

[golang]
format = 'via [$symbol]($style)'

[nodejs]
format = 'via [$symbol]($style)'

[python]
format = 'via [$symbol]($style)'

[rust]
format = 'via [$symbol]($style)'
symbol = " "

[swift]
format = 'via [$symbol]($style)'
