require("mini.base16").setup({
  palette = {
    base00 = "#101010",
    base01 = "#161616",
    base02 = "#242525",
    base03 = "#515051",
    base04 = "#A0A0A0",
    base05 = "#f5f5f5",
    base06 = "#f5f5f5",
    base07 = "#ffffff",
    base08 = "#FF8080",
    base09 = "#6ad0b7",
    base0A = "#f5f5f5",
    base0B = "#6ad0b7",
    base0C = "#6A9589",
    base0D = "#FFC799",
    base0E = "#A0A0A0",
    base0F = "#A0A0A0",
  },
})
vim.g.colors_name = "ember"

local peach, grey, bg, border = "#FFCFA8", "#A0A0A0", "#101010", "#282828"
local hl = {
  Identifier = { fg = peach },
  Exception = { fg = peach },
  Boolean = { fg = "#6ad0b7" },
  Operator = { fg = grey },
  ["@variable"] = { fg = peach },
  ["@property"] = { fg = peach },
  ["@variable.member"] = { fg = peach },
  ["@type.builtin"] = { fg = peach },
  ["@operator"] = { fg = grey },
  ["@keyword.import"] = { fg = grey },
  ["@tag.attribute"] = { fg = peach },
  ["@variable.parameter"] = { fg = "#f5f5f5" },
  TreesitterContext = { bg = "#1e1f1f" },
  Whitespace = { fg = "#312D2A" },
  NonText = { fg = "#312D2A" },
  SnacksPickerDir = { fg = grey },
  SnacksPickerSearch = { fg = peach, bg = "#4a3626", bold = true },
  PmenuSel = { bg = "#242525" },

  DiffAdd = { bg = "#16302a" },
  DiffDelete = { bg = "#3a1c1c" },
  DiffChange = { bg = "#1e1f1f" },
  DiffText = { bg = "#3d3020" },

  LineNr = { fg = "#515051", bg = bg },
  SignColumn = { bg = bg },
  FoldColumn = { fg = "#515051", bg = bg },
  CursorLineNr = { fg = grey, bg = bg },

  StatusLine = { fg = grey, bg = "#161616" },
  StatusLineNC = { fg = "#515051", bg = "#161616" },

  WinSeparator = { fg = border, bg = bg },
  VertSplit = { fg = border, bg = bg },
  SnacksWinSeparator = { fg = bg, bg = bg },
  FloatBorder = { fg = border, bg = bg },
  NormalFloat = { fg = "#f5f5f5", bg = bg },
  SnacksPickerBorder = { fg = border, bg = bg },
  SnacksPickerBoxBorder = { fg = border, bg = bg },
  SnacksPickerInputBorder = { fg = border, bg = bg },
  SnacksPickerListBorder = { fg = border, bg = bg },
  SnacksPickerPreviewBorder = { fg = border, bg = bg },

  -- render-markdown
  RenderMarkdownH1 = { fg = peach, bold = true },
  RenderMarkdownH2 = { fg = "#FFC799", bold = true },
  RenderMarkdownH3 = { fg = "#6ad0b7", bold = true },
  RenderMarkdownH4 = { fg = "#6A9589", bold = true },
  RenderMarkdownH5 = { fg = grey, bold = true },
  RenderMarkdownH6 = { fg = "#515051", bold = true },
  RenderMarkdownH1Bg = { fg = peach, bg = "#2b221b" },
  RenderMarkdownH2Bg = { fg = "#FFC799", bg = "#211b16" },
  RenderMarkdownH3Bg = { fg = "#6ad0b7", bg = "#15211e" },
  RenderMarkdownH4Bg = { fg = "#6A9589", bg = "#141a18" },
  RenderMarkdownH5Bg = { fg = grey, bg = "#181818" },
  RenderMarkdownH6Bg = { fg = "#515051", bg = "#141414" },
  RenderMarkdownCode = { bg = "#161616" },
  RenderMarkdownCodeBorder = { bg = "#1c1c1c" },
  RenderMarkdownCodeInfo = { fg = grey, italic = true },
  RenderMarkdownCodeInline = { fg = peach, bg = "#1e1f1f" },
  RenderMarkdownQuote = { fg = grey, italic = true },
  RenderMarkdownBullet = { fg = peach },
  RenderMarkdownDash = { fg = border },
  RenderMarkdownLink = { fg = "#6ad0b7", underline = true },
  RenderMarkdownLinkTitle = { fg = "#6ad0b7" },
  RenderMarkdownWikiLink = { fg = "#6ad0b7", underline = true },
  RenderMarkdownUnchecked = { fg = grey },
  RenderMarkdownChecked = { fg = "#6ad0b7" },
  RenderMarkdownTodo = { fg = peach },
  RenderMarkdownTableHead = { fg = peach, bold = true },
  RenderMarkdownTableRow = { fg = grey },
  RenderMarkdownMath = { fg = "#FFC799" },
  RenderMarkdownHtmlComment = { fg = "#515051", italic = true },
  RenderMarkdownSuccess = { fg = "#6ad0b7" },
  RenderMarkdownInfo = { fg = "#6A9589" },
  RenderMarkdownHint = { fg = grey },
  RenderMarkdownWarn = { fg = "#FFC799" },
  RenderMarkdownError = { fg = "#FF8080" },
}
for name, val in pairs(hl) do
  vim.api.nvim_set_hl(0, name, val)
end
