# reload config
unbind r
bind r source-file ~/.tmux.conf

# pass throught
set -g allow-passthrough on

# enable vim mode
set-window-option -g mode-keys vi

# clear scrollback
bind -n C-l send-keys C-l \; clear-history

set-option -g status-position top
set -g default-terminal "tmux-256color"

# start windows from 1
set -g base-index 1

# renumber windows after deleting one
set -g renumber-windows on

# set leader
set -g prefix C-s

# enable mouse
set -g mouse on

# copy and paste
set -g @yank_action 'copy-pipe'

# vim like pane nav
bind-key h select-pane -L
bind-key j select-pane -D
bind-key k select-pane -U
bind-key l select-pane -R

# List of plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-yank'

# theme
color_fg="#f5f5f5"
color_fg_accent="#ffcfa8"
color_fg_green="#6ad0b7"
color_bg="#161616"
color_bg_light="#242525"
color_border="#282828"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-style "fg=${color_fg},bg=default"
set -g status-left "#[fg=${color_fg_accent},bold,bg=${color_bg}] [󰇥 #S] "
set -g status-right "#[bg=${color_bg}]  #h "
set -g window-status-current-format "#[bg=${color_bg},fg=${color_fg_green}] #I:#W "
set -g window-status-format "#[bg=${color_bg}] #I:#W "
set -g message-style "fg=${color_fg},bg=default"
set -g mode-style "fg=${color_fg_accent},bg=${color_bg_light}"
set -g pane-border-style "fg=${color_border}"
set -g pane-active-border-style "fg=${color_border}"
set -g window-status-separator ''

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
